# -*- coding = utf-8 -*-
# @Time : 2022/4/6 13:10
# @Author : 谢扬筱
# @File : URL.py

URLS = {
    "Normal Baseline Data": {
        "Normal_0": "https://engineering.case.edu/sites/default/files/97.mat",
        "Normal_1": "https://engineering.case.edu/sites/default/files/98.mat",
        "Normal_2": "https://engineering.case.edu/sites/default/files/99.mat",
        "Normal_3": "https://engineering.case.edu/sites/default/files/100.mat",
    },
    "12k Drive End Bearing Fault Data": {
        "IR007_0": "https://engineering.case.edu/sites/default/files/105.mat",
        "IR007_1": "https://engineering.case.edu/sites/default/files/106.mat",
        "IR007_2": "https://engineering.case.edu/sites/default/files/107.mat",
        "IR007_3": "https://engineering.case.edu/sites/default/files/108.mat",
        "IR014_0": "https://engineering.case.edu/sites/default/files/169.mat",
        "IR014_1": "https://engineering.case.edu/sites/default/files/170.mat",
        "IR014_2": "https://engineering.case.edu/sites/default/files/171.mat",
        "IR014_3": "https://engineering.case.edu/sites/default/files/172.mat",
        "IR021_0": "https://engineering.case.edu/sites/default/files/209.mat",
        "IR021_1": "https://engineering.case.edu/sites/default/files/210.mat",
        "IR021_2": "https://engineering.case.edu/sites/default/files/211.mat",
        "IR021_3": "https://engineering.case.edu/sites/default/files/212.mat",
        "IR028_0": "https://engineering.case.edu/sites/default/files/3001.mat",
        "IR028_1": "https://engineering.case.edu/sites/default/files/3002.mat",
        "IR028_2": "https://engineering.case.edu/sites/default/files/3003.mat",
        "IR028_3": "https://engineering.case.edu/sites/default/files/3004.mat",
        "B007_0": "https://engineering.case.edu/sites/default/files/118.mat",
        "B007_1": "https://engineering.case.edu/sites/default/files/119.mat",
        "B007_2": "https://engineering.case.edu/sites/default/files/120.mat",
        "B007_3": "https://engineering.case.edu/sites/default/files/121.mat",
        "B014_0": "https://engineering.case.edu/sites/default/files/185.mat",
        "B014_1": "https://engineering.case.edu/sites/default/files/186.mat",
        "B014_2": "https://engineering.case.edu/sites/default/files/187.mat",
        "B014_3": "https://engineering.case.edu/sites/default/files/188.mat",
        "B021_0": "https://engineering.case.edu/sites/default/files/222.mat",
        "B021_1": "https://engineering.case.edu/sites/default/files/223.mat",
        "B021_2": "https://engineering.case.edu/sites/default/files/224.mat",
        "B021_3": "https://engineering.case.edu/sites/default/files/225.mat",
        "B028_0": "https://engineering.case.edu/sites/default/files/3005.mat",
        "B028_1": "https://engineering.case.edu/sites/default/files/3006.mat",
        "B028_2": "https://engineering.case.edu/sites/default/files/3007.mat",
        "B028_3": "https://engineering.case.edu/sites/default/files/3008.mat",
        "OR007@6_0": "https://engineering.case.edu/sites/default/files/130.mat",
        "OR007@6_1": "https://engineering.case.edu/sites/default/files/131.mat",
        "OR007@6_2": "https://engineering.case.edu/sites/default/files/132.mat",
        "OR007@6_3": "https://engineering.case.edu/sites/default/files/133.mat",
        "OR014@6_0": "https://engineering.case.edu/sites/default/files/197.mat",
        "OR014@6_1": "https://engineering.case.edu/sites/default/files/198.mat",
        "OR014@6_2": "https://engineering.case.edu/sites/default/files/199.mat",
        "OR014@6_3": "https://engineering.case.edu/sites/default/files/200.mat",
        "OR021@6_0": "https://engineering.case.edu/sites/default/files/234.mat",
        "OR021@6_1": "https://engineering.case.edu/sites/default/files/235.mat",
        "OR021@6_2": "https://engineering.case.edu/sites/default/files/236.mat",
        "OR021@6_3": "https://engineering.case.edu/sites/default/files/237.mat",
        "OR007@3_0": "https://engineering.case.edu/sites/default/files/144.mat",
        "OR007@3_1": "https://engineering.case.edu/sites/default/files/145.mat",
        "OR007@3_2": "https://engineering.case.edu/sites/default/files/146.mat",
        "OR007@3_3": "https://engineering.case.edu/sites/default/files/147.mat",
        "OR021@3_0": "https://engineering.case.edu/sites/default/files/246.mat",
        "OR021@3_1": "https://engineering.case.edu/sites/default/files/247.mat",
        "OR021@3_2": "https://engineering.case.edu/sites/default/files/248.mat",
        "OR021@3_3": "https://engineering.case.edu/sites/default/files/249.mat",
        "OR007@12_0": "https://engineering.case.edu/sites/default/files/156.mat",
        "OR007@12_1": "https://engineering.case.edu/sites/default/files/158.mat",
        "OR007@12_2": "https://engineering.case.edu/sites/default/files/159.mat",
        "OR007@12_3": "https://engineering.case.edu/sites/default/files/160.mat",
        "OR021@12_0": "https://engineering.case.edu/sites/default/files/258.mat",
        "OR021@12_1": "https://engineering.case.edu/sites/default/files/259.mat",
        "OR021@12_2": "https://engineering.case.edu/sites/default/files/260.mat",
        "OR021@12_3": "https://engineering.case.edu/sites/default/files/261.mat",
    },
    "48k Drive End Bearking Fault Data":{
        "IR007_0" : "https://engineering.case.edu/sites/default/files/109.mat",
        "IR007_1" : "https://engineering.case.edu/sites/default/files/110.mat",
        "IR007_2" : "https://engineering.case.edu/sites/default/files/111.mat",
        "IR007_3" : "https://engineering.case.edu/sites/default/files/112.mat",
        "IR014_0" : "https://engineering.case.edu/sites/default/files/174.mat",
        "IR014_1" : "https://engineering.case.edu/sites/default/files/175.mat",
        "IR014_2" : "https://engineering.case.edu/sites/default/files/176.mat",
        "IR014_3" : "https://engineering.case.edu/sites/default/files/177.mat",
        "IR021_0" : "https://engineering.case.edu/sites/default/files/213.mat",
        "IR021_1" : "https://engineering.case.edu/sites/default/files/214.mat",
        "IR021_2" : "https://engineering.case.edu/sites/default/files/215.mat",
        "IR021_3" : "https://engineering.case.edu/sites/default/files/217.mat",
        "B007_0" : "https://engineering.case.edu/sites/default/files/122.mat",
        "B007_1" : "https://engineering.case.edu/sites/default/files/123.mat",
        "B007_2" : "https://engineering.case.edu/sites/default/files/124.mat",
        "B007_3" : "https://engineering.case.edu/sites/default/files/125.mat",
        "B014_0" : "https://engineering.case.edu/sites/default/files/189.mat",
        "B014_1" : "https://engineering.case.edu/sites/default/files/190.mat",
        "B014_2" : "https://engineering.case.edu/sites/default/files/191.mat",
        "B014_3" : "https://engineering.case.edu/sites/default/files/192.mat",
        "B021_0" : "https://engineering.case.edu/sites/default/files/226.mat",
        "B021_1" : "https://engineering.case.edu/sites/default/files/227.mat",
        "B021_2" : "https://engineering.case.edu/sites/default/files/228.mat",
        "B021_3" : "https://engineering.case.edu/sites/default/files/229.mat",
        "OR007@6_0" : "https://engineering.case.edu/sites/default/files/135.mat",
        "OR007@6_1" : "https://engineering.case.edu/sites/default/files/136.mat",
        "OR007@6_2" : "https://engineering.case.edu/sites/default/files/137.mat",
        "OR007@6_3" : "https://engineering.case.edu/sites/default/files/138.mat",
        "OR014@6_0" : "https://engineering.case.edu/sites/default/files/201.mat",
        "OR014@6_1" : "https://engineering.case.edu/sites/default/files/202.mat",
        "OR014@6_2" : "https://engineering.case.edu/sites/default/files/203.mat",
        "OR014@6_3" : "https://engineering.case.edu/sites/default/files/204.mat",
        "OR021@6_0" : "https://engineering.case.edu/sites/default/files/238.mat",
        "OR021@6_1" : "https://engineering.case.edu/sites/default/files/239.mat",
        "OR021@6_2" : "https://engineering.case.edu/sites/default/files/240.mat",
        "OR021@6_3" : "https://engineering.case.edu/sites/default/files/241.mat",
        "OR007@3_0" : "https://engineering.case.edu/sites/default/files/148.mat",
        "OR007@3_1" : "https://engineering.case.edu/sites/default/files/149.mat",
        "OR007@3_2" : "https://engineering.case.edu/sites/default/files/150.mat",
        "OR007@3_3" : "https://engineering.case.edu/sites/default/files/151.mat",
        "OR021@3_0" : "https://engineering.case.edu/sites/default/files/250.mat",
        "OR021@3_1" : "https://engineering.case.edu/sites/default/files/251.mat",
        "OR021@3_2" : "https://engineering.case.edu/sites/default/files/252.mat",
        "OR021@3_3" : "https://engineering.case.edu/sites/default/files/253.mat",
        "OR007@12_0" : "https://engineering.case.edu/sites/default/files/161.mat",
        "OR007@12_1" : "https://engineering.case.edu/sites/default/files/162.mat",
        "OR007@12_2" : "https://engineering.case.edu/sites/default/files/163.mat",
        "OR007@12_3" : "https://engineering.case.edu/sites/default/files/164.mat",
        "OR021@12_0" : "https://engineering.case.edu/sites/default/files/262.mat",
        "OR021@12_1" : "https://engineering.case.edu/sites/default/files/263.mat",
        "OR021@12_2" : "https://engineering.case.edu/sites/default/files/264.mat",
        "OR021@12_3" : "https://engineering.case.edu/sites/default/files/265.mat",
    },
    "12k Fan End Bearing Fault Data":{
        "IR007_0" : "https://engineering.case.edu/sites/default/files/278.mat",
        "IR007_1" : "https://engineering.case.edu/sites/default/files/279.mat",
        "IR007_2" : "https://engineering.case.edu/sites/default/files/280.mat",
        "IR007_3" : "https://engineering.case.edu/sites/default/files/281.mat",
        "IR014_0" : "https://engineering.case.edu/sites/default/files/274.mat",
        "IR014_1" : "https://engineering.case.edu/sites/default/files/275.mat",
        "IR014_2" : "https://engineering.case.edu/sites/default/files/276.mat",
        "IR014_3" : "https://engineering.case.edu/sites/default/files/277.mat",
        "IR021_0" : "https://engineering.case.edu/sites/default/files/270.mat",
        "IR021_1" : "https://engineering.case.edu/sites/default/files/271.mat",
        "IR021_2" : "https://engineering.case.edu/sites/default/files/272.mat",
        "IR021_3" : "https://engineering.case.edu/sites/default/files/273.mat",
        "B007_0" : "https://engineering.case.edu/sites/default/files/282.mat",
        "B007_1" : "https://engineering.case.edu/sites/default/files/283.mat",
        "B007_2" : "https://engineering.case.edu/sites/default/files/284.mat",
        "B007_3" : "https://engineering.case.edu/sites/default/files/285.mat",
        "B014_0" : "https://engineering.case.edu/sites/default/files/286.mat",
        "B014_1" : "https://engineering.case.edu/sites/default/files/287.mat",
        "B014_2" : "https://engineering.case.edu/sites/default/files/288.mat",
        "B014_3" : "https://engineering.case.edu/sites/default/files/289.mat",
        "B021_0" : "https://engineering.case.edu/sites/default/files/290.mat",
        "B021_1" : "https://engineering.case.edu/sites/default/files/291.mat",
        "B021_2" : "https://engineering.case.edu/sites/default/files/292.mat",
        "B021_3" : "https://engineering.case.edu/sites/default/files/293.mat",
        "OR007@6_0" : "https://engineering.case.edu/sites/default/files/294.mat",
        "OR007@6_1" : "https://engineering.case.edu/sites/default/files/295.mat",
        "OR007@6_2" : "https://engineering.case.edu/sites/default/files/296.mat",
        "OR007@6_3" : "https://engineering.case.edu/sites/default/files/297.mat",
        "OR014@6_0" : "https://engineering.case.edu/sites/default/files/313.mat",
        "OR021@6_0" : "https://engineering.case.edu/sites/default/files/315.mat",
        "OR007@3_0" : "https://engineering.case.edu/sites/default/files/298.mat",
        "OR007@3_1" : "https://engineering.case.edu/sites/default/files/299.mat",
        "OR007@3_2" : "https://engineering.case.edu/sites/default/files/300.mat",
        "OR007@3_3" : "https://engineering.case.edu/sites/default/files/301.mat",
        "OR014@3_0" : "https://engineering.case.edu/sites/default/files/310.mat",
        "OR014@3_1" : "https://engineering.case.edu/sites/default/files/309.mat",
        "OR014@3_2" : "https://engineering.case.edu/sites/default/files/311.mat",
        "OR014@3_3" : "https://engineering.case.edu/sites/default/files/312.mat",
        "OR021@3_1" : "https://engineering.case.edu/sites/default/files/316.mat",
        "OR021@3_2" : "https://engineering.case.edu/sites/default/files/317.mat",
        "OR021@3_3" : "https://engineering.case.edu/sites/default/files/318.mat",
        "OR007@12_0" : "https://engineering.case.edu/sites/default/files/302.mat",
        "OR007@12_1" : "https://engineering.case.edu/sites/default/files/305.mat",
        "OR007@12_2" : "https://engineering.case.edu/sites/default/files/306.mat",
        "OR007@12_3": "https://engineering.case.edu/sites/default/files/307.mat",
    }
}
